### ISSUE TITLE
Issue with Record Wrangling Tutorial

### ISSUE THREAD

**Issue by akhilpotla** [vanderbilt-redcap/external-module-framework-docs#8] opened 2024-02-13 22:40 UTC
I have been following [this tutorial](https://github.com/vanderbilt-redcap/external-module-framework-docs/blob/main/guide.md) that is geared towards beginners from this repository. I have not had any issues so far, but when attempting the record wrangling section of the guide I get the following error when attempting to upload the XML file that corresponds to that step in the tutorial:

```
REDCap crashed due to an unexpected PHP fatal error!

Error message: Uncaught Error: Data must be loaded before reading in redcap_v13.7.31/Classes/ODM.php:2437 Stack trace: #0 redcap_v13.7.31/Classes/ODM.php(2437): XMLReader->read() #1 redcap_v13.7.31/Classes/ODM.php(1588): ODM::validateOdmInitial('<?xml version="...') #2 redcap_v13.7.31/ProjectGeneral/create_project.php(1062): ODM::parseOdm('<?xml version="...') #3 {main} thrown
File: redcap_v13.7.31/Classes/ODM.php
Line: 2437
```

From what it looks like, I think it is an issue with the [php file from the tutorial](https://github.com/vanderbilt-redcap/external-module-framework-docs/blob/main/exercises/record_wrangling/RecordWranglingModule.php); however, I was not able to deduce what the issue is. If it's not the php file, it is probably the xml file itself.

Any help would be greatly appreciated.

**Comment by mmcev106** [comment] 2024-02-14 16:38
@akhilpotla, thanks for reaching out!  I just loaded version 13.7.31 on my computer and tried this exercise, but was unable to reproduce the issue.  I did have to make a couple of changes to the example solution (and updated the docs accordingly).  However, I don't think those relate to your issue.

You mentioned you thought it was an issue with a PHP file from the tutorial.  It doesn't seem like that could be the case to me, as no files from the tutorial are in use while uploading the XML file.  I wonder if there is some other issue on your system (e.g. a temp dir permissions issue).  If you go to the  `Configuration Check` page in `Control Center`, do you see any errors there?  If not, and you are able to reproduce this problem repeatedly, I would recommend posting on [redcap.vanderbilt.edu/community](https://redcap.vanderbilt.edu/community/) and tagging Rob Taylor.  Feel free to tag me as well if you, but I'm not sure I'll be able to help further with this type of issue.

I'm going to close this for now, as it does not seem related to the external module framework.  Feel free to reopen it if I'm missing something!

**Closed by mmcev106** 2024-02-14 16:38 UTC
